### PR TITLE
fix: curl 7.82 reporting bad URL

### PR DESCRIPTION
**Pull request by iysheng**
Because when I use dmenu to triger d, then i found the issue #1 is still occur. So I think the line put here is more suite for all situations.

### CODE REVIEW

**Review by klesh — COMMENTED** [review]
Aah, good one, but line 79 is not being deleted, would you mind to rebase and delete it?

**Comment by iysheng** [comment]
> 
I'm a little sorry, can I revert the commit 8f5afa161cc751784d16aa1bd08db5dad2cbee14 from you, and then replace it use this pr? :face_exhaling: Or I must push based on the commit 8f5afa161cc751784d16aa1bd08db5dad2cbee14 ? Maybe this is the first time of me to handle with this condition.

**Comment by klesh** [comment]
@iysheng sorry for replying late. Even if I did revert my last commit, you will still have to rebase because of my HEAD commit will be a branch new commit. Maybe I can force push my main branch but this is not a good practice.
Let me show you the standard way for this kind of issue:

1. Add my repo as one of you remote upstream: `git remote add upstream https://github.com/klesh/dict.sh.git`
2. Then, fetch data from upstream: `git fetch upstream`, this operation would only download data from my repo, will not affect your local repo at all.
3. Now, rebase: `git rebase upstream main`, this operation reapply your commits on top my `main` branch as if you  started off from my latest main branch. You may run into `conflict`, but that is alright, just modify conflicted files, save them, stage them with `git add <files>` , and then, type `git rebase --resume` to apply your changes.
4. Finally, you get a rebased branch, push it to your repo with `git push -f`, and this PR will be renew automatically. We need the `-f` flag because the commit history was modified, github wont accept it unless the `-f` was given.

**Comment by iysheng** [comment]
> @iysheng sorry for replying late. Even if I did revert my last commit, you will still have to rebase because of my HEAD commit will be a branch new commit. Maybe I can force push my main branch but this is not a good practice. Let me show you the standard way for this kind of issue:
> 
>     1. Add my repo as one of you remote upstream: `git remote add upstream https://github.com/klesh/dict.sh.git`
> 
>     2. Then, fetch data from upstream: `git fetch upstream`, this operation would only download data from my repo, will not affect your local repo at all.
> 
>     3. Now, rebase: `git rebase upstream main`, this operation reapply your commits on top my `main` branch as if you  started off from my latest main branch. You may run into `conflict`, but that is alright, just modify conflicted files, save them, stage them with `git add <files>` , and then, type `git rebase --resume` to apply your changes.
> 
>     4. Finally, you get a rebased branch, push it to your repo with `git push -f`, and this PR will be renew automatically. We need the `-f` flag because the commit history was modified, github wont accept it unless the `-f` was given.

thanks for your patient reply. I do follow your command. Hope this time right?😂

**Comment by klesh** [comment]
Thank you for doing that, nice job!

**Pull request merged**
